// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: Api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EngineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	EngineType    int32                  `protobuf:"varint,3,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	ModelPath     string                 `protobuf:"bytes,4,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	Names         []string               `protobuf:"bytes,5,rep,name=names,proto3" json:"names,omitempty"`
	Confidence    float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Iou           float32                `protobuf:"fixed32,7,opt,name=iou,proto3" json:"iou,omitempty"`
	UseGpu        bool                   `protobuf:"varint,8,opt,name=use_gpu,json=useGpu,proto3" json:"use_gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineInfo) Reset() {
	*x = EngineInfo{}
	mi := &file_Api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineInfo) ProtoMessage() {}

func (x *EngineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineInfo.ProtoReflect.Descriptor instead.
func (*EngineInfo) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{0}
}

func (x *EngineInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EngineInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EngineInfo) GetEngineType() int32 {
	if x != nil {
		return x.EngineType
	}
	return 0
}

func (x *EngineInfo) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *EngineInfo) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *EngineInfo) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *EngineInfo) GetIou() float32 {
	if x != nil {
		return x.Iou
	}
	return 0
}

func (x *EngineInfo) GetUseGpu() bool {
	if x != nil {
		return x.UseGpu
	}
	return false
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_Api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SingleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Box           []*Position            `protobuf:"bytes,3,rep,name=box,proto3" json:"box,omitempty"`
	Center        *Position              `protobuf:"bytes,4,opt,name=center,proto3" json:"center,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleResult) Reset() {
	*x = SingleResult{}
	mi := &file_Api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleResult) ProtoMessage() {}

func (x *SingleResult) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleResult.ProtoReflect.Descriptor instead.
func (*SingleResult) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{2}
}

func (x *SingleResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SingleResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SingleResult) GetBox() []*Position {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *SingleResult) GetCenter() *Position {
	if x != nil {
		return x.Center
	}
	return nil
}

type InitEngineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EngineType    int32                  `protobuf:"varint,1,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	ModelPath     string                 `protobuf:"bytes,2,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	Names         []string               `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Iou           float32                `protobuf:"fixed32,6,opt,name=iou,proto3" json:"iou,omitempty"`
	UseGpu        bool                   `protobuf:"varint,7,opt,name=use_gpu,json=useGpu,proto3" json:"use_gpu,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEngineRequest) Reset() {
	*x = InitEngineRequest{}
	mi := &file_Api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEngineRequest) ProtoMessage() {}

func (x *InitEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEngineRequest.ProtoReflect.Descriptor instead.
func (*InitEngineRequest) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{3}
}

func (x *InitEngineRequest) GetEngineType() int32 {
	if x != nil {
		return x.EngineType
	}
	return 0
}

func (x *InitEngineRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *InitEngineRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *InitEngineRequest) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *InitEngineRequest) GetIou() float32 {
	if x != nil {
		return x.Iou
	}
	return 0
}

func (x *InitEngineRequest) GetUseGpu() bool {
	if x != nil {
		return x.UseGpu
	}
	return false
}

func (x *InitEngineRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type InitEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEngineResponse) Reset() {
	*x = InitEngineResponse{}
	mi := &file_Api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEngineResponse) ProtoMessage() {}

func (x *InitEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEngineResponse.ProtoReflect.Descriptor instead.
func (*InitEngineResponse) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{4}
}

func (x *InitEngineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitEngineResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InitEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImgData       []byte                 `protobuf:"bytes,2,opt,name=img_data,json=imgData,proto3" json:"img_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_Api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{5}
}

func (x *InferenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InferenceRequest) GetImgData() []byte {
	if x != nil {
		return x.ImgData
	}
	return nil
}

type InferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results       []*SingleResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_Api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{6}
}

func (x *InferenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InferenceResponse) GetResults() []*SingleResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DestroyEngineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyEngineRequest) Reset() {
	*x = DestroyEngineRequest{}
	mi := &file_Api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyEngineRequest) ProtoMessage() {}

func (x *DestroyEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyEngineRequest.ProtoReflect.Descriptor instead.
func (*DestroyEngineRequest) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyEngineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DestroyEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyEngineResponse) Reset() {
	*x = DestroyEngineResponse{}
	mi := &file_Api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyEngineResponse) ProtoMessage() {}

func (x *DestroyEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyEngineResponse.ProtoReflect.Descriptor instead.
func (*DestroyEngineResponse) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{8}
}

func (x *DestroyEngineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestroyEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckEngineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEngineRequest) Reset() {
	*x = CheckEngineRequest{}
	mi := &file_Api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEngineRequest) ProtoMessage() {}

func (x *CheckEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEngineRequest.ProtoReflect.Descriptor instead.
func (*CheckEngineRequest) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{9}
}

func (x *CheckEngineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EngineInfo    *EngineInfo            `protobuf:"bytes,2,opt,name=engine_info,json=engineInfo,proto3" json:"engine_info,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEngineResponse) Reset() {
	*x = CheckEngineResponse{}
	mi := &file_Api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEngineResponse) ProtoMessage() {}

func (x *CheckEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEngineResponse.ProtoReflect.Descriptor instead.
func (*CheckEngineResponse) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{10}
}

func (x *CheckEngineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckEngineResponse) GetEngineInfo() *EngineInfo {
	if x != nil {
		return x.EngineInfo
	}
	return nil
}

func (x *CheckEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckAllEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Engines       []*EngineInfo          `protobuf:"bytes,2,rep,name=engines,proto3" json:"engines,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAllEngineResponse) Reset() {
	*x = CheckAllEngineResponse{}
	mi := &file_Api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAllEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAllEngineResponse) ProtoMessage() {}

func (x *CheckAllEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAllEngineResponse.ProtoReflect.Descriptor instead.
func (*CheckAllEngineResponse) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{11}
}

func (x *CheckAllEngineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckAllEngineResponse) GetEngines() []*EngineInfo {
	if x != nil {
		return x.Engines
	}
	return nil
}

func (x *CheckAllEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_Api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{12}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFileRequest_FileInfo
	//	*UploadFileRequest_ChunkData
	Data          isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_Api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{13}
}

func (x *UploadFileRequest) GetData() isUploadFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetFileInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_FileInfo); ok {
			return x.FileInfo
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type UploadFileRequest_FileInfo struct {
	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3,oneof"`
}

type UploadFileRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadFileRequest_FileInfo) isUploadFileRequest_Data() {}

func (*UploadFileRequest_ChunkData) isUploadFileRequest_Data() {}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_Api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{14}
}

func (x *UploadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFileResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

var File_Api_proto protoreflect.FileDescriptor

const file_Api_proto_rawDesc = "" +
	"\n" +
	"\tApi.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\xdf\x01\n" +
	"\n" +
	"EngineInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vengine_type\x18\x03 \x01(\x05R\n" +
	"engineType\x12\x1d\n" +
	"\n" +
	"model_path\x18\x04 \x01(\tR\tmodelPath\x12\x14\n" +
	"\x05names\x18\x05 \x03(\tR\x05names\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\x12\x10\n" +
	"\x03iou\x18\a \x01(\x02R\x03iou\x12\x17\n" +
	"\ause_gpu\x18\b \x01(\bR\x06useGpu\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\x8e\x01\n" +
	"\fSingleResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\x03box\x18\x03 \x03(\v2\x0f.proto.PositionR\x03box\x12'\n" +
	"\x06center\x18\x04 \x01(\v2\x0f.proto.PositionR\x06center\"\xd6\x01\n" +
	"\x11InitEngineRequest\x12\x1f\n" +
	"\vengine_type\x18\x01 \x01(\x05R\n" +
	"engineType\x12\x1d\n" +
	"\n" +
	"model_path\x18\x02 \x01(\tR\tmodelPath\x12\x14\n" +
	"\x05names\x18\x03 \x03(\tR\x05names\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x10\n" +
	"\x03iou\x18\x06 \x01(\x02R\x03iou\x12\x17\n" +
	"\ause_gpu\x18\a \x01(\bR\x06useGpu\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"X\n" +
	"\x12InitEngineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"=\n" +
	"\x10InferenceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bimg_data\x18\x02 \x01(\fR\aimgData\"\\\n" +
	"\x11InferenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\aresults\x18\x02 \x03(\v2\x13.proto.SingleResultR\aresults\"&\n" +
	"\x14DestroyEngineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x15DestroyEngineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\x12CheckEngineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"}\n" +
	"\x13CheckEngineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\vengine_info\x18\x02 \x01(\v2\x11.proto.EngineInfoR\n" +
	"engineInfo\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"y\n" +
	"\x16CheckAllEngineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\aengines\x18\x02 \x03(\v2\x11.proto.EngineInfoR\aengines\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"O\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\"l\n" +
	"\x11UploadFileRequest\x12.\n" +
	"\tfile_info\x18\x01 \x01(\v2\x0f.proto.FileInfoH\x00R\bfileInfo\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"e\n" +
	"\x12UploadFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath2\xef\x03\n" +
	"\rDetectService\x12A\n" +
	"\n" +
	"InitEngine\x12\x18.proto.InitEngineRequest\x1a\x19.proto.InitEngineResponse\x12>\n" +
	"\tInference\x12\x17.proto.InferenceRequest\x1a\x18.proto.InferenceResponse\x12J\n" +
	"\rDestroyEngine\x12\x1b.proto.DestroyEngineRequest\x1a\x1c.proto.DestroyEngineResponse\x12D\n" +
	"\vCheckEngine\x12\x19.proto.CheckEngineRequest\x1a\x1a.proto.CheckEngineResponse\x12G\n" +
	"\x0eCheckAllEngine\x12\x16.google.protobuf.Empty\x1a\x1d.proto.CheckAllEngineResponse\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\vUploadModel\x12\x18.proto.UploadFileRequest\x1a\x19.proto.UploadFileResponse(\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_Api_proto_rawDescOnce sync.Once
	file_Api_proto_rawDescData []byte
)

func file_Api_proto_rawDescGZIP() []byte {
	file_Api_proto_rawDescOnce.Do(func() {
		file_Api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Api_proto_rawDesc), len(file_Api_proto_rawDesc)))
	})
	return file_Api_proto_rawDescData
}

var file_Api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_Api_proto_goTypes = []any{
	(*EngineInfo)(nil),             // 0: proto.EngineInfo
	(*Position)(nil),               // 1: proto.Position
	(*SingleResult)(nil),           // 2: proto.SingleResult
	(*InitEngineRequest)(nil),      // 3: proto.InitEngineRequest
	(*InitEngineResponse)(nil),     // 4: proto.InitEngineResponse
	(*InferenceRequest)(nil),       // 5: proto.InferenceRequest
	(*InferenceResponse)(nil),      // 6: proto.InferenceResponse
	(*DestroyEngineRequest)(nil),   // 7: proto.DestroyEngineRequest
	(*DestroyEngineResponse)(nil),  // 8: proto.DestroyEngineResponse
	(*CheckEngineRequest)(nil),     // 9: proto.CheckEngineRequest
	(*CheckEngineResponse)(nil),    // 10: proto.CheckEngineResponse
	(*CheckAllEngineResponse)(nil), // 11: proto.CheckAllEngineResponse
	(*FileInfo)(nil),               // 12: proto.FileInfo
	(*UploadFileRequest)(nil),      // 13: proto.UploadFileRequest
	(*UploadFileResponse)(nil),     // 14: proto.UploadFileResponse
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
}
var file_Api_proto_depIdxs = []int32{
	1,  // 0: proto.SingleResult.box:type_name -> proto.Position
	1,  // 1: proto.SingleResult.center:type_name -> proto.Position
	2,  // 2: proto.InferenceResponse.results:type_name -> proto.SingleResult
	0,  // 3: proto.CheckEngineResponse.engine_info:type_name -> proto.EngineInfo
	0,  // 4: proto.CheckAllEngineResponse.engines:type_name -> proto.EngineInfo
	12, // 5: proto.UploadFileRequest.file_info:type_name -> proto.FileInfo
	3,  // 6: proto.DetectService.InitEngine:input_type -> proto.InitEngineRequest
	5,  // 7: proto.DetectService.Inference:input_type -> proto.InferenceRequest
	7,  // 8: proto.DetectService.DestroyEngine:input_type -> proto.DestroyEngineRequest
	9,  // 9: proto.DetectService.CheckEngine:input_type -> proto.CheckEngineRequest
	15, // 10: proto.DetectService.CheckAllEngine:input_type -> google.protobuf.Empty
	15, // 11: proto.DetectService.Shutdown:input_type -> google.protobuf.Empty
	13, // 12: proto.DetectService.UploadModel:input_type -> proto.UploadFileRequest
	4,  // 13: proto.DetectService.InitEngine:output_type -> proto.InitEngineResponse
	6,  // 14: proto.DetectService.Inference:output_type -> proto.InferenceResponse
	8,  // 15: proto.DetectService.DestroyEngine:output_type -> proto.DestroyEngineResponse
	10, // 16: proto.DetectService.CheckEngine:output_type -> proto.CheckEngineResponse
	11, // 17: proto.DetectService.CheckAllEngine:output_type -> proto.CheckAllEngineResponse
	15, // 18: proto.DetectService.Shutdown:output_type -> google.protobuf.Empty
	14, // 19: proto.DetectService.UploadModel:output_type -> proto.UploadFileResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_Api_proto_init() }
func file_Api_proto_init() {
	if File_Api_proto != nil {
		return
	}
	file_Api_proto_msgTypes[13].OneofWrappers = []any{
		(*UploadFileRequest_FileInfo)(nil),
		(*UploadFileRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Api_proto_rawDesc), len(file_Api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Api_proto_goTypes,
		DependencyIndexes: file_Api_proto_depIdxs,
		MessageInfos:      file_Api_proto_msgTypes,
	}.Build()
	File_Api_proto = out.File
	file_Api_proto_goTypes = nil
	file_Api_proto_depIdxs = nil
}
