// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: Api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DetectService_InitEngine_FullMethodName     = "/proto.DetectService/InitEngine"
	DetectService_Inference_FullMethodName      = "/proto.DetectService/Inference"
	DetectService_DestroyEngine_FullMethodName  = "/proto.DetectService/DestroyEngine"
	DetectService_CheckEngine_FullMethodName    = "/proto.DetectService/CheckEngine"
	DetectService_CheckAllEngine_FullMethodName = "/proto.DetectService/CheckAllEngine"
	DetectService_Shutdown_FullMethodName       = "/proto.DetectService/Shutdown"
)

// DetectServiceClient is the client API for DetectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectServiceClient interface {
	// 5. 修改这里：参数引用新的 Request 名字
	InitEngine(ctx context.Context, in *InitEngineRequest, opts ...grpc.CallOption) (*InitEngineResponse, error)
	// 6. 修改这里
	Inference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error)
	// 7. 修改这里
	DestroyEngine(ctx context.Context, in *DestroyEngineRequest, opts ...grpc.CallOption) (*DestroyEngineResponse, error)
	// 8. 修改这里
	CheckEngine(ctx context.Context, in *CheckEngineRequest, opts ...grpc.CallOption) (*CheckEngineResponse, error)
	CheckAllEngine(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CheckAllEngineResponse, error)
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type detectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectServiceClient(cc grpc.ClientConnInterface) DetectServiceClient {
	return &detectServiceClient{cc}
}

func (c *detectServiceClient) InitEngine(ctx context.Context, in *InitEngineRequest, opts ...grpc.CallOption) (*InitEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitEngineResponse)
	err := c.cc.Invoke(ctx, DetectService_InitEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectServiceClient) Inference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResponse)
	err := c.cc.Invoke(ctx, DetectService_Inference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectServiceClient) DestroyEngine(ctx context.Context, in *DestroyEngineRequest, opts ...grpc.CallOption) (*DestroyEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyEngineResponse)
	err := c.cc.Invoke(ctx, DetectService_DestroyEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectServiceClient) CheckEngine(ctx context.Context, in *CheckEngineRequest, opts ...grpc.CallOption) (*CheckEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEngineResponse)
	err := c.cc.Invoke(ctx, DetectService_CheckEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectServiceClient) CheckAllEngine(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CheckAllEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAllEngineResponse)
	err := c.cc.Invoke(ctx, DetectService_CheckAllEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectServiceClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DetectService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectServiceServer is the server API for DetectService service.
// All implementations must embed UnimplementedDetectServiceServer
// for forward compatibility.
type DetectServiceServer interface {
	// 5. 修改这里：参数引用新的 Request 名字
	InitEngine(context.Context, *InitEngineRequest) (*InitEngineResponse, error)
	// 6. 修改这里
	Inference(context.Context, *InferenceRequest) (*InferenceResponse, error)
	// 7. 修改这里
	DestroyEngine(context.Context, *DestroyEngineRequest) (*DestroyEngineResponse, error)
	// 8. 修改这里
	CheckEngine(context.Context, *CheckEngineRequest) (*CheckEngineResponse, error)
	CheckAllEngine(context.Context, *emptypb.Empty) (*CheckAllEngineResponse, error)
	Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedDetectServiceServer()
}

// UnimplementedDetectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectServiceServer struct{}

func (UnimplementedDetectServiceServer) InitEngine(context.Context, *InitEngineRequest) (*InitEngineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitEngine not implemented")
}
func (UnimplementedDetectServiceServer) Inference(context.Context, *InferenceRequest) (*InferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Inference not implemented")
}
func (UnimplementedDetectServiceServer) DestroyEngine(context.Context, *DestroyEngineRequest) (*DestroyEngineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyEngine not implemented")
}
func (UnimplementedDetectServiceServer) CheckEngine(context.Context, *CheckEngineRequest) (*CheckEngineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckEngine not implemented")
}
func (UnimplementedDetectServiceServer) CheckAllEngine(context.Context, *emptypb.Empty) (*CheckAllEngineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAllEngine not implemented")
}
func (UnimplementedDetectServiceServer) Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDetectServiceServer) mustEmbedUnimplementedDetectServiceServer() {}
func (UnimplementedDetectServiceServer) testEmbeddedByValue()                       {}

// UnsafeDetectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectServiceServer will
// result in compilation errors.
type UnsafeDetectServiceServer interface {
	mustEmbedUnimplementedDetectServiceServer()
}

func RegisterDetectServiceServer(s grpc.ServiceRegistrar, srv DetectServiceServer) {
	// If the following call panics, it indicates UnimplementedDetectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetectService_ServiceDesc, srv)
}

func _DetectService_InitEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectServiceServer).InitEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectService_InitEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectServiceServer).InitEngine(ctx, req.(*InitEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectService_Inference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectServiceServer).Inference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectService_Inference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectServiceServer).Inference(ctx, req.(*InferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectService_DestroyEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectServiceServer).DestroyEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectService_DestroyEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectServiceServer).DestroyEngine(ctx, req.(*DestroyEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectService_CheckEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectServiceServer).CheckEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectService_CheckEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectServiceServer).CheckEngine(ctx, req.(*CheckEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectService_CheckAllEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectServiceServer).CheckAllEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectService_CheckAllEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectServiceServer).CheckAllEngine(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectServiceServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectService_ServiceDesc is the grpc.ServiceDesc for DetectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DetectService",
	HandlerType: (*DetectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitEngine",
			Handler:    _DetectService_InitEngine_Handler,
		},
		{
			MethodName: "Inference",
			Handler:    _DetectService_Inference_Handler,
		},
		{
			MethodName: "DestroyEngine",
			Handler:    _DetectService_DestroyEngine_Handler,
		},
		{
			MethodName: "CheckEngine",
			Handler:    _DetectService_CheckEngine_Handler,
		},
		{
			MethodName: "CheckAllEngine",
			Handler:    _DetectService_CheckAllEngine_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DetectService_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Api.proto",
}
